const clientsData = {
    Tomáš: {
      age: 28,
      weight: 80,
      height: 180,
      benchPress: 100,
      squat: 120,
      deadlift: 150,
      burnedCalories: 2500,  
      distance: 5.2,        
      steps: 10234,         
      mealPlan: {
        "Pondělí": [
          { meal: "Snídaně", food: "Ovesné vločky s proteinem", grams: "100g", kcal: "350" },
          { meal: "Svačina", food: "Mandle a jablko", grams: "50g", kcal: "250" },
          { meal: "Oběd", food: "Kuřecí prsa s rýží", grams: "200g", kcal: "600" },
          { meal: "Svačina", food: "Tvaroh s ořechy", grams: "150g", kcal: "300" },
          { meal: "Večeře", food: "Losos s batáty", grams: "220g", kcal: "550" },
        ],
        "Úterý": [
          { meal: "Snídaně", food: "Rohlík se šunkou", grams: "100g", kcal: "280" },
          { meal: "Svačina", food: "Banán", grams: "120g", kcal: "105" },
          { meal: "Oběd", food: "Hovězí steak s bramborem", grams: "250g", kcal: "650" },
          { meal: "Svačina", food: "Proteinový shake", grams: "300ml", kcal: "400" },
          { meal: "Večeře", food: "Losos na grilu", grams: "200g", kcal: "450" },
        ],
        "Středa": [
          { meal: "Snídaně", food: "Pohanková kaše s ovocem", grams: "120g", kcal: "360" },
          { meal: "Svačina", food: "Kefír a ořechy", grams: "200g", kcal: "320" },
          { meal: "Oběd", food: "Vepřová panenka s kuskusem", grams: "250g", kcal: "640" },
          { meal: "Svačina", food: "Proteinová tyčinka", grams: "60g", kcal: "250" },
          { meal: "Večeře", food: "Tuňákový salát s avokádem", grams: "220g", kcal: "500" },
        ],
        "Čtvrtek": [
          { meal: "Snídaně", food: "Vaječná omeleta s špenátem", grams: "150g", kcal: "380" },
          { meal: "Svačina", food: "Tvaroh s medem", grams: "180g", kcal: "280" },
          { meal: "Oběd", food: "Grilované kuře s batáty", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Cottage s celozrnným chlebem", grams: "150g", kcal: "290" },
          { meal: "Večeře", food: "Hovězí tatarák s vejcem", grams: "200g", kcal: "540" },
        ],
        "Pátek": [
          { meal: "Snídaně", food: "Palačinky s tvarohem", grams: "200g", kcal: "420" },
          { meal: "Svačina", food: "Jablko s arašídovým máslem", grams: "150g", kcal: "290" },
          { meal: "Oběd", food: "Losos s rýží a brokolicí", grams: "250g", kcal: "680" },
          { meal: "Svačina", food: "Mandle a sušené ovoce", grams: "80g", kcal: "350" },
          { meal: "Večeře", food: "Grilovaná zelenina s tofu", grams: "220g", kcal: "460" },
        ],
        "Sobota": [
          { meal: "Snídaně", food: "Chia pudink s ovocem", grams: "150g", kcal: "300" },
          { meal: "Svačina", food: "Proteinová tyčinka", grams: "60g", kcal: "250" },
          { meal: "Oběd", food: "Krůtí maso s batátovou kaší", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Ovesné sušenky s medem", grams: "100g", kcal: "380" },
          { meal: "Večeře", food: "Míchaný salát s kuřecím masem", grams: "220g", kcal: "480" },
        ],
        "Neděle": [
          { meal: "Snídaně", food: "Tousty s avokádem a vejcem", grams: "180g", kcal: "400" },
          { meal: "Svačina", food: "Tvaroh se semínky", grams: "150g", kcal: "290" },
          { meal: "Oběd", food: "Hovězí guláš s bramborem", grams: "250g", kcal: "700" },
          { meal: "Svačina", food: "Ořechová směs", grams: "80g", kcal: "350" },
          { meal: "Večeře", food: "Ryba na másle se zeleninou", grams: "220g", kcal: "510" },
        ],
      },
      workoutPlan: {
        "Pondělí": [
          { exercise: "Dřepy", sets: "4", reps: "10" },
          { exercise: "Leg Press", sets: "4", reps: "12" },
          { exercise: "Výpady", sets: "3", reps: "15" },
          { exercise: "Lýtka na stroji", sets: "4", reps: "20" },
          { exercise: "Plank", sets: "3", reps: "60s" },
        ],
        "Úterý": [
          { exercise: "Bench Press", sets: "4", reps: "8" },
          { exercise: "Kliky na bradlech", sets: "3", reps: "12" },
          { exercise: "Tlaky s jednoručkami", sets: "4", reps: "10" },
          { exercise: "Upažování", sets: "3", reps: "15" },
          { exercise: "Bicepsové zdvihy", sets: "4", reps: "12" },
        ],
        "Středa": [
          { exercise: "Mrtvý tah", sets: "4", reps: "8" },
          { exercise: "Přítahy na hrazdě", sets: "3", reps: "10" },
          { exercise: "T-tyč přítahy", sets: "4", reps: "12" },
          { exercise: "Lýtka na stroji", sets: "4", reps: "20" },
          { exercise: "Sklapovačky", sets: "3", reps: "20" },
        ],
        "Čtvrtek": [
          { exercise: "Ramenní tlak", sets: "4", reps: "10" },
          { exercise: "Upažování", sets: "3", reps: "15" },
          { exercise: "Tlaky s jednoručkami nad hlavu", sets: "4", reps: "12" },
          { exercise: "Farmářská chůze", sets: "3", reps: "30s" },
          { exercise: "Rotace s kotoučem", sets: "3", reps: "12" },
        ],
        "Pátek": [
          { exercise: "Dřepy s činkou", sets: "4", reps: "8" },
          { exercise: "Výpady", sets: "3", reps: "12" },
          { exercise: "Zakopávání", sets: "4", reps: "15" },
          { exercise: "Výpony na lýtka", sets: "3", reps: "20" },
          { exercise: "Švihadlo", sets: "4", reps: "1 min" },
        ],
        "Sobota": [
          { exercise: "Dřepy s činkou", sets: "4", reps: "10" },
          { exercise: "Mrtvý tah", sets: "4", reps: "10" },
          { exercise: "Výpady s jednoručkami", sets: "3", reps: "12" },
          { exercise: "Farmářská chůze", sets: "3", reps: "30s" },
          { exercise: "Rotace s kotoučem", sets: "3", reps: "12" },
        ],
        "Neděle": [
          { exercise: "Odpočinek", sets: "-", reps: "-" },
          { exercise: "Lehké kardio", sets: "1", reps: "20 min" },
          { exercise: "Protahování celého těla", sets: "1", reps: "10 min" },
          { exercise: "Jóga / mobilita", sets: "1", reps: "15 min" },
          { exercise: "Chůze venku", sets: "1", reps: "30 min" },
        ],  
      },
    },
  
    Anna: {
      age: 22,
      weight: 65,
      height: 170,
      benchPress: 50,
      squat: 90,
      deadlift: 110,
      burnedCalories: 2500,  // Nové údaje
      distance: 5.2,         // Nové údaje
      steps: 10234,         // Nové údaje
      mealPlan: {
        "Pondělí": [
          { meal: "Snídaně", food: "Ovesná kaše s ořechy", grams: "120g", kcal: "380" },
          { meal: "Svačina", food: "Jogurt s ovocem", grams: "200g", kcal: "220" },
          { meal: "Oběd", food: "Grilované kuře s quinoou", grams: "250g", kcal: "550" },
          { meal: "Svačina", food: "Cottage s celozrnným chlebem", grams: "150g", kcal: "290" },
          { meal: "Večeře", food: "Losos s avokádovým salátem", grams: "220g", kcal: "500" },
        ],
        "Úterý": [
          { meal: "Snídaně", food: "Proteinové palačinky s medem", grams: "150g", kcal: "420" },
          { meal: "Svačina", food: "Mandle a jablko", grams: "80g", kcal: "300" },
          { meal: "Oběd", food: "Krůtí plátek s kuskusem", grams: "250g", kcal: "600" },
          { meal: "Svačina", food: "Tvaroh se semínky", grams: "150g", kcal: "280" },
          { meal: "Večeře", food: "Grilovaná zelenina s tofu", grams: "220g", kcal: "480" },
        ],
        "Středa": [
          { meal: "Snídaně", food: "Banánový smoothie s vločkami", grams: "300ml", kcal: "350" },
          { meal: "Svačina", food: "Proteinová tyčinka", grams: "60g", kcal: "250" },
          { meal: "Oběd", food: "Losos na másle s bramborem", grams: "250g", kcal: "680" },
          { meal: "Svačina", food: "Cottage s medem", grams: "150g", kcal: "290" },
          { meal: "Večeře", food: "Kuřecí wrap s avokádem", grams: "200g", kcal: "550" },
        ],
        "Čtvrtek": [
          { meal: "Snídaně", food: "Tvarohová kaše s ovocem", grams: "120g", kcal: "360" },
          { meal: "Svačina", food: "Ořechy a sušené ovoce", grams: "80g", kcal: "280" },
          { meal: "Oběd", food: "Hovězí steak s rýží", grams: "250g", kcal: "700" },
          { meal: "Svačina", food: "Proteinový shake", grams: "300ml", kcal: "400" },
          { meal: "Večeře", food: "Těstoviny s kuřecím masem", grams: "250g", kcal: "600" },
        ],
        "Pátek": [
          { meal: "Snídaně", food: "Míchaná vejce s avokádem", grams: "150g", kcal: "400" },
          { meal: "Svačina", food: "Bílý jogurt s borůvkami", grams: "180g", kcal: "220" },
          { meal: "Oběd", food: "Grilované kuřecí prsa s quinoou", grams: "250g", kcal: "600" },
          { meal: "Svačina", food: "Mandle a jablko", grams: "80g", kcal: "300" },
          { meal: "Večeře", food: "Cizrnový salát s tofu", grams: "220g", kcal: "450" },
        ],
        "Sobota": [
          { meal: "Snídaně", food: "Ovesné sušenky s banánem", grams: "150g", kcal: "380" },
          { meal: "Svačina", food: "Kefír s ořechy", grams: "200g", kcal: "320" },
          { meal: "Oběd", food: "Kuřecí stir-fry se zeleninou", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Proteinová tyčinka", grams: "60g", kcal: "250" },
          { meal: "Večeře", food: "Zeleninový salát s feta sýrem", grams: "220g", kcal: "480" },
        ],
        "Neděle": [
          { meal: "Snídaně", food: "Smoothie bowl s ovocem", grams: "300ml", kcal: "350" },
          { meal: "Svačina", food: "Tvaroh s medem a semínky", grams: "150g", kcal: "290" },
          { meal: "Oběd", food: "Hovězí guláš s bramborem", grams: "250g", kcal: "700" },
          { meal: "Svačina", food: "Ořechová směs", grams: "80g", kcal: "350" },
          { meal: "Večeře", food: "Losos na másle se zeleninou", grams: "220g", kcal: "510" },
        ],
      },
      workoutPlan: {
        "Pondělí": [
          { exercise: "Dřepy s činkou", sets: "3", reps: "12" },
          { exercise: "Mrtvý tah", sets: "4", reps: "10" },
          { exercise: "Rumunský mrtvý tah", sets: "3", reps: "12" },
          { exercise: "Výpady", sets: "3", reps: "15" },
          { exercise: "Břicho - zkracovačky", sets: "3", reps: "20" },
        ],
        "Úterý": [
          { exercise: "Tlaky s jednoručkami", sets: "4", reps: "10" },
          { exercise: "Bicepsové zdvihy", sets: "3", reps: "12" },
          { exercise: "Tricepsové kliky", sets: "3", reps: "15" },
          { exercise: "Farmářská chůze", sets: "3", reps: "30s" },
          { exercise: "Plank", sets: "3", reps: "60s" },
        ],
        "Středa": [
          { exercise: "Dřepy s kettlebellem", sets: "4", reps: "12" },
          { exercise: "Přítahy kladky", sets: "3", reps: "10" },
          { exercise: "Hip thrust", sets: "4", reps: "12" },
          { exercise: "Lýtka na stroji", sets: "4", reps: "20" },
          { exercise: "Sklapovačky", sets: "3", reps: "20" },
        ],
        "Čtvrtek": [
          { exercise: "Ramenní tlak", sets: "4", reps: "10" },
          { exercise: "Upažování s činkami", sets: "3", reps: "15" },
          { exercise: "Tlaky na strojích", sets: "4", reps: "12" },
          { exercise: "Plank s váhou", sets: "3", reps: "60s" },
          { exercise: "Švihadlo", sets: "4", reps: "1 min" },
        ],
        "Pátek": [
          { exercise: "Dřepy", sets: "4", reps: "10" },
          { exercise: "Zakopávání na stroji", sets: "3", reps: "12" },
          { exercise: "Výpady s jednoručkami", sets: "4", reps: "12" },
          { exercise: "Dynamický plank", sets: "3", reps: "45s" },
          { exercise: "Švihadlo", sets: "4", reps: "1 min" },
        ],
        "Sobota": [
          { exercise: "Dřepy s činkou", sets: "4", reps: "10" },
          { exercise: "Mrtvý tah", sets: "4", reps: "10" },
          { exercise: "Výpady s jednoručkami", sets: "3", reps: "12" },
          { exercise: "Farmářská chůze", sets: "3", reps: "30s" },
          { exercise: "Rotace s kotoučem", sets: "3", reps: "12" },
        ],
        "Neděle": [
          { exercise: "Odpočinek", sets: "-", reps: "-" },
          { exercise: "Lehké kardio", sets: "1", reps: "20 min" },
          { exercise: "Protahování celého těla", sets: "1", reps: "10 min" },
          { exercise: "Jóga / mobilita", sets: "1", reps: "15 min" },
          { exercise: "Chůze venku", sets: "1", reps: "30 min" },
        ],  
      },
    },
    
  
    Petr: {
      age: 25,
      weight: 85,
      height: 175,
      benchPress: 110,
      squat: 130,
      deadlift: 160,
      burnedCalories: 2500,  // Nové údaje
      distance: 5.2,         // Nové údaje
      steps: 10234,         // Nové údaje
      mealPlan: {
        "Pondělí": [
          { meal: "Snídaně", food: "Vajíčka s pečivem", grams: "150g", kcal: "400" },
          { meal: "Svačina", food: "Proteinový koktejl", grams: "300ml", kcal: "420" },
          { meal: "Oběd", food: "Hovězí burger bez housky", grams: "250g", kcal: "680" },
          { meal: "Svačina", food: "Mandle a sušené ovoce", grams: "80g", kcal: "350" },
          { meal: "Večeře", food: "Treska s rýží", grams: "220g", kcal: "480" },
        ],
        "Úterý": [
          { meal: "Snídaně", food: "Celozrnný chléb se šunkou", grams: "120g", kcal: "320" },
          { meal: "Svačina", food: "Ořechová směs", grams: "80g", kcal: "350" },
          { meal: "Oběd", food: "Kuřecí stir-fry s rýží", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Proteinová tyčinka", grams: "60g", kcal: "250" },
          { meal: "Večeře", food: "Tuňákový salát", grams: "220g", kcal: "500" },
        ],
        "Středa": [
          { meal: "Snídaně", food: "Proteinové palačinky", grams: "150g", kcal: "420" },
          { meal: "Svačina", food: "Banán", grams: "120g", kcal: "105" },
          { meal: "Oběd", food: "Hovězí steak s bramborem", grams: "250g", kcal: "700" },
          { meal: "Svačina", food: "Bílý jogurt s medem", grams: "180g", kcal: "280" },
          { meal: "Večeře", food: "Grilovaný losos se zeleninou", grams: "220g", kcal: "550" },
        ],
        "Čtvrtek": [
          { meal: "Snídaně", food: "Ovesná kaše s proteinem", grams: "120g", kcal: "360" },
          { meal: "Svačina", food: "Mandle a sušené ovoce", grams: "80g", kcal: "350" },
          { meal: "Oběd", food: "Krůtí prsa s batáty", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Tvaroh s ovocem", grams: "150g", kcal: "290" },
          { meal: "Večeře", food: "Hovězí guláš s bramborem", grams: "250g", kcal: "750" },
        ],
        "Pátek": [
          { meal: "Snídaně", food: "Míchaná vejce s avokádem", grams: "150g", kcal: "400" },
          { meal: "Svačina", food: "Proteinový koktejl", grams: "300ml", kcal: "420" },
          { meal: "Oběd", food: "Kuřecí prsa s rýží", grams: "250g", kcal: "620" },
          { meal: "Svačina", food: "Cottage s celozrnným chlebem", grams: "150g", kcal: "300" },
          { meal: "Večeře", food: "Treska na másle se zeleninou", grams: "220g", kcal: "500" },
        ],
        "Sobota": [
          { meal: "Snídaně", food: "Tvarohová kaše s medem", grams: "150g", kcal: "380" },
          { meal: "Svačina", food: "Jogurt s ovocem", grams: "200g", kcal: "220" },
          { meal: "Oběd", food: "Hovězí steak s batáty", grams: "250g", kcal: "680" },
          { meal: "Svačina", food: "Ořechová směs", grams: "80g", kcal: "350" },
          { meal: "Večeře", food: "Cizrnový salát s lososem", grams: "220g", kcal: "550" },
        ],
        "Neděle": [
          { meal: "Snídaně", food: "Smoothie bowl s proteinem", grams: "300ml", kcal: "350" },
          { meal: "Svačina", food: "Tvaroh se semínky", grams: "150g", kcal: "290" },
          { meal: "Oběd", food: "Grilované kuřecí stehno s rýží", grams: "250g", kcal: "650" },
          { meal: "Svačina", food: "Bílý jogurt s medem", grams: "180g", kcal: "280" },
          { meal: "Večeře", food: "Losos na másle s quinoou", grams: "220g", kcal: "520" },
        ],
      },
      workoutPlan: {
        "Pondělí": [
          { exercise: "Bench Press", sets: "4", reps: "10" },
          { exercise: "Tlaky na ramena", sets: "4", reps: "10" },
          { exercise: "Bicepsový zdvih s činkami", sets: "4", reps: "12" },
          { exercise: "Tricepsové kliky", sets: "3", reps: "15" },
          { exercise: "Břicho - plank", sets: "3", reps: "60s" },
        ],
        "Úterý": [
          { exercise: "Dřepy s činkou", sets: "4", reps: "10" },
          { exercise: "Leg Press", sets: "4", reps: "12" },
          { exercise: "Výpady", sets: "3", reps: "15" },
          { exercise: "Lýtka na stroji", sets: "4", reps: "20" },
          { exercise: "Sklapovačky", sets: "3", reps: "20" },
        ],
        "Středa": [
          { exercise: "Mrtvý tah", sets: "4", reps: "10" },
          { exercise: "Přítahy kladky", sets: "3", reps: "10" },
          { exercise: "Tlaky na stroji", sets: "4", reps: "12" },
          { exercise: "Plank s váhou", sets: "3", reps: "60s" },
          { exercise: "Švihadlo", sets: "4", reps: "1 min" },
        ],
        "Čtvrtek": [
          { exercise: "Bicepsové zdvihy", sets: "4", reps: "12" },
          { exercise: "Francouzský tlak", sets: "3", reps: "12" },
          { exercise: "Hammer curls", sets: "4", reps: "10" },
          { exercise: "Tricepsové kliky", sets: "3", reps: "12" },
          { exercise: "Stahování kladky na triceps", sets: "4", reps: "15" },
        ],
        "Pátek": [
          { exercise: "Bench Press", sets: "4", reps: "10" },
          { exercise: "Tlaky na ramena", sets: "4", reps: "10" },
          { exercise: "Bicepsový zdvih", sets: "4", reps: "12" },
          { exercise: "Tricepsové kliky", sets: "3", reps: "15" },
          { exercise: "Břicho - plank", sets: "3", reps: "60s" },
        ],
        "Sobota": [
          { exercise: "Dřepy s činkou", sets: "4", reps: "10" },
          { exercise: "Mrtvý tah", sets: "4", reps: "10" },
          { exercise: "Výpady s jednoručkami", sets: "3", reps: "12" },
          { exercise: "Farmářská chůze", sets: "3", reps: "30s" },
          { exercise: "Rotace s kotoučem", sets: "3", reps: "12" },
        ],
        "Neděle": [
          { exercise: "Odpočinek", sets: "-", reps: "-" },
          { exercise: "Lehké kardio", sets: "1", reps: "20 min" },
          { exercise: "Protahování celého těla", sets: "1", reps: "10 min" },
          { exercise: "Jóga / mobilita", sets: "1", reps: "15 min" },
          { exercise: "Chůze venku", sets: "1", reps: "30 min" },
        ],        
      },
    },
 }
  
 export default clientsData;